/-
Copyright (c) 2026 Arav Paladiya. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Arav Paladiya
-/
module

public import Mathlib.Algebra.Group.Subgroup.Lattice
public import Mathlib.GroupTheory.FreeAbelianGroup
public import Mathlib.GroupTheory.QuotientGroup.Defs
public import Mathlib.RingTheory.Factorization.DivisorTheory.Basic

/-!
# Divisor class groups

This file constructs the group of divisors associated to a free divisor monoid and quotients it
by the subgroup generated by principal divisors.

## Main definitions

* `DivisorGroup P`: the free abelian group on the prime divisors `P`.
* `principalDivisors φ`: the subgroup generated by the nonzero divisors in the image of `φ`.
* `DivisorClassGroup φ`: the quotient of the divisor group by its principal divisors.
* `DivisorTheory.ClassGroup D`: the class group of an explicit bundled divisor theory.

## Main results

* `DivisorClassGroup.mk_surjective`: every divisor class has a divisor representative.
* `DivisorClassGroup.quotientMulEquiv`: transport across a divisor-group equivalence that
  identifies the principal subgroups.
* `DivisorClassGroup.mk_eq_one_iff`: a divisor has trivial class exactly when it is principal.

## Implementation notes

`DivisorClassGroup` is opaque. Consumers should use its projection, surjectivity, trivial-class,
and quotient-equivalence APIs rather than its quotient representation.
-/

public section

assert_not_exists Field FractionalIdeal Ideal

universe u v w

variable {α : Type u} {P : Type w}

/-- The group of divisors over a type `P`: the free abelian group on `P`, written
multiplicatively. -/
abbrev DivisorGroup (P : Type u) : Type u := Multiplicative (FreeAbelianGroup P)

namespace FreeDivisorMonoid

/-- The canonical embedding of the free monoid of divisors into the group of divisors. -/
def toDivisorGroup (P : Type*) : FreeDivisorMonoid P →* DivisorGroup P :=
  AddMonoidHom.toMultiplicative
    { toFun := fun s ↦ (s.map FreeAbelianGroup.of).sum
      map_zero' := rfl
      map_add' := fun s t ↦ by simp }

/-- The canonical embedding sends a multiset of prime divisors to the sum of its free
generators. -/
@[simp]
theorem toDivisorGroup_apply (d : FreeDivisorMonoid P) :
    (toDivisorGroup P d).toAdd = (d.toAdd.map FreeAbelianGroup.of).sum := by
  simp [toDivisorGroup]
  rfl

/-- The prime basis divisor maps to the corresponding generator of the divisor group. -/
@[simp]
theorem toDivisorGroup_of (p : P) :
    toDivisorGroup P (of p) = Multiplicative.ofAdd (FreeAbelianGroup.of p) := by
  apply Multiplicative.toAdd.injective
  rw [toDivisorGroup_apply]
  simp

/-- The canonical embedding of the free divisor monoid into its group of fractions is
injective. -/
theorem toDivisorGroup_injective : Function.Injective (toDivisorGroup P) := by
  classical
  intro s t hst
  apply Multiplicative.toAdd.injective
  apply Multiset.ext.mpr
  intro p
  let e : FreeAbelianGroup P →+ ℤ :=
    FreeAbelianGroup.lift fun q ↦ if p = q then 1 else 0
  have heval (r : Multiset P) :
      e ((r.map FreeAbelianGroup.of).sum) = r.count p := by
    induction r using Multiset.induction_on with
    | empty => simp [e]
    | @cons q r ih => simp [e, ih, Multiset.count_cons, add_comm]
  have h := congrArg (fun z : DivisorGroup P ↦ e (Multiplicative.toAdd z)) hst
  change e (((Multiplicative.toAdd s).map FreeAbelianGroup.of).sum) =
    e (((Multiplicative.toAdd t).map FreeAbelianGroup.of).sum) at h
  rw [heval, heval] at h
  exact_mod_cast h

end FreeDivisorMonoid

section DivisorClassGroup

variable [CommMonoidWithZero α]

/-- The subgroup generated by the nonzero divisors in the image of `φ`. The zero of
`DivisorMonoid P` is excluded by the coercion from `FreeDivisorMonoid P`. -/
def principalDivisors (φ : α →*₀ DivisorMonoid P) : Subgroup (DivisorGroup P) :=
  Subgroup.closure (FreeDivisorMonoid.toDivisorGroup P ''
    {d : FreeDivisorMonoid P | ∃ a : α, φ a = (d : DivisorMonoid P)})

/-- The subgroup of principal divisors is the subgroup generated by the positive divisors in
the image. -/
theorem principalDivisors_eq_closure (φ : α →*₀ DivisorMonoid P) :
    principalDivisors φ = Subgroup.closure (FreeDivisorMonoid.toDivisorGroup P ''
      {d : FreeDivisorMonoid P | ∃ a : α, φ a = (d : DivisorMonoid P)}) := by
  rw [principalDivisors]

/-- A positive divisor in the image of `φ` belongs to the subgroup of principal divisors. -/
theorem mem_principalDivisors_of_eq {φ : α →*₀ DivisorMonoid P}
    {d : FreeDivisorMonoid P} {a : α} (h : φ a = (d : DivisorMonoid P)) :
    FreeDivisorMonoid.toDivisorGroup P d ∈ principalDivisors φ := by
  apply Subgroup.subset_closure
  exact ⟨d, ⟨a, h⟩, rfl⟩

/-- The quotient of the divisor group by the subgroup of principal divisors. -/
def DivisorClassGroup (φ : α →*₀ DivisorMonoid P) : Type w :=
  DivisorGroup P ⧸ principalDivisors φ
deriving CommGroup

/-- The canonical projection of a divisor to its divisor class. -/
def DivisorClassGroup.mk (φ : α →*₀ DivisorMonoid P) :
    DivisorGroup P →* DivisorClassGroup φ :=
  QuotientGroup.mk' (principalDivisors φ)

/-- The canonical projection from divisors to divisor classes is surjective. -/
theorem DivisorClassGroup.mk_surjective (φ : α →*₀ DivisorMonoid P) :
    Function.Surjective (DivisorClassGroup.mk φ) :=
  QuotientGroup.mk'_surjective _

/-- Transport a divisor class group across an equivalence of divisor groups that identifies
their subgroups of principal divisors. -/
def DivisorClassGroup.quotientMulEquiv {G : Type v} [CommGroup G]
    (φ : α →*₀ DivisorMonoid P) (H : Subgroup G) (E : DivisorGroup P ≃* G)
    (hE : (principalDivisors φ).map E = H) :
    DivisorClassGroup φ ≃* G ⧸ H :=
  QuotientGroup.congr _ _ E hE

/-- The quotient equivalence sends a divisor class to the class of the corresponding divisor. -/
@[simp]
theorem DivisorClassGroup.quotientMulEquiv_mk {G : Type v} [CommGroup G]
    (φ : α →*₀ DivisorMonoid P) (H : Subgroup G) (E : DivisorGroup P ≃* G)
    (hE : (principalDivisors φ).map E = H) (x : DivisorGroup P) :
    DivisorClassGroup.quotientMulEquiv φ H E hE (DivisorClassGroup.mk φ x) =
      QuotientGroup.mk' H (E x) := by
  change (QuotientGroup.congr (principalDivisors φ) H E hE)
    (QuotientGroup.mk' (principalDivisors φ) x) = QuotientGroup.mk' H (E x)
  exact QuotientGroup.congr_mk' (principalDivisors φ) H E hE x

/-- A divisor has trivial class exactly when it belongs to the subgroup of principal
divisors. -/
theorem DivisorClassGroup.mk_eq_one_iff (φ : α →*₀ DivisorMonoid P)
    (x : DivisorGroup P) :
    DivisorClassGroup.mk φ x = 1 ↔ x ∈ principalDivisors φ := by
  change (x : DivisorGroup P ⧸ principalDivisors φ) = 1 ↔ x ∈ principalDivisors φ
  exact QuotientGroup.eq_one_iff x

namespace DivisorTheory

/-- The class group attached to an explicit bundled divisor theory. -/
abbrev ClassGroup (D : DivisorTheory α P) : Type w :=
  DivisorClassGroup D.toMonoidWithZeroHom

end DivisorTheory

end DivisorClassGroup
